### PR TITLE
Use place details info when selecting location due to language issues

### PR DESCRIPTION
**Pull request by chalenascholl**
[JIRA Ticket](https://convoy.atlassian.net/browse/CFW-3995)

We've been getting errors in the backend when we try to parse location for state searches. This is because the locations we are trying to parse are states like Carolina del Norte and Nueva York. Apparently, even if you pass 'en' as the language to the google places API it doesn't actually restrict the options to english results. So if something you type matches a different language result it'll return that.

However, if you then use the place ID to get the place details and pass the 'en' language, it'll return place details in that language.

I originally opened an [issue with google](https://issuetracker.google.com/u/0/issues/207389476) but they responded saying this is how it's supposed to work.

ALTERNATIVELY, this is only relevant for state search and happens pretty infrequently (maybe around once a day), so we can also opt to not fix this if we don't like changing this or feel that it's hacky. IMO, this fix makes sense and is the only workaround I can think of. It's also kind of crappy to allow users to select a location and then not actually do the search because we don't know what it means...

image
image

### CODE REVIEW

**Comment by gfoltz** [comment]
Let me get this straight:

1.) User types "Carolina" in the search box
2.) Google places API returns "Carolina del Norte" in the  autocomplete list. 
3.) Spanish speaking user taps on that
4.) GoogleAutocomplete components fetches a details request for the corresponding PlaceID ... and the place ID is a place that represents the state of North Carolina in the Spanish locale. The resulting `rowData` has 'Carolina del Norte' in the `description` field. 
5.) Convoy app uses the description as the search input

So the fix is to modify the description to be the results of the response `formatted_address` field instead?  What is the `terms` field for?

**Comment by chalenascholl** [comment]
Mostly correct. Corrections below:
4) "and the place ID is a place that represents the state of North Carolina in the Spanish locale" -> No. The place ID represents the place itself and returns details about that place in the language specified, in our case english. 
    - The distinction here is that the autocomplete results list uses the language as more of a ranking helper than a hard rule. So if you type the spanish word for a place or something that closely matches the spanish word, it will still show that in the results list despite us passing the 'en' language parameter.
    - `RowData` is what is returned by the autocomplete results list. The `formatted_address` comes from the 2nd request we make for the place details
    
Here's a basic flow:
1) User enters Carolina
2) We make a request to `places/autocomplete/?input=carolina`
3) We get a list of autocomplete suggestions, each of which we refer to as `RowData`
4) User taps on a location (i.e. Carolina del Norte)
5) We make a request to `place/details` using the place ID which we do to get the coordinates, however for description we continue using `RowData`.
6) Now the issue: `RowData` can have the description and terms in a different language.
7) Solution: Use the `formatted_address` we get from the place details request because that should always be in english since it strictly adheres to the 'en' language parameter

The terms field separates each component of the address into a list like so and provides what the type of each is.
image

image

**Comment by gfoltz** [comment]
I think I'd be more comfortable with this if we: 1.) did something more targeted to the specific problem and also 2.) did this in chalupa-mobile instead of adding onto our fork of this component.

For (1): It looks like the autocomplete result returns a 'types' array and we only want to patch up the state when the 'type' includes "administrative_area_level_1" (i.e. a state).

For (2): It looks like it's not possible completely, but we could get away with a much smaller and arguably better fix to this library. The component already passes the entire rowData back to the `onPress` handler supplied by Chalupa. So I think we could fairly easily implement the meat of this workaround in chalupa itself.  What we can't do is the part that adds `formatted_address` to the set of fields to request in the details query. It looks like just an oversight that the poorly named `autocompleteFields` prop was not added as an official prop in https://github.com/convoyinc/react-native-google-places-autocomplete/pull/3

I'd suggest that we fix the component by officially exposing `autocompleteFields` as a prop of this component. Then move the rest of this PR into chalupa. While we're here, I think we should probably rename the field name `autocompleteFieldss` to `detailQueryFields` or something that is a better descriptor. OR, we could rename it to match the upstream code, which currently has a field named GooglePlacesDetailsQuery. See https://github.com/FaridSafi/react-native-google-places-autocomplete


As a total aside, this package is 2 years behind upstream. We should look into what it would take to bring this up to date with the latest and greatest.

**Comment by chalenascholl** [comment]
@gfoltz
1) I think that makes sense.
2) We can pass an additional field to the component if we specify the prop `GooglePlacesDetailsQuery` as `{ fields: autoCompleteFields }`. I initially started to fix it that way but the reasons I decided to fix it in the package instead are:
    a) Fixing it in the package means it will also fix it in older versions of the app since we only specify a branch and that is mutable (debatably a disadvantage as well, though in this case I'm not sure how it would harm older versions of the app)
    b) The mobile app is the only place we use this package so instead of applying fixes to multiple places in our app, why not apply a fix in the main location so that it works as one would expect it to? Since we are passing `en` it's counter intuitive (IMO) that it would return results in any other language.
    c) Fixing it in the app means that we have to apply the fix in at least the following 2 methods: `shortenedDescription` and `buildLocationFromSelection` which means we have to apply the fix twice, rather than just once at the main source.

**Comment by gfoltz** [comment]
>Fixing it in the package means it will also fix it in older versions of the app since we only specify a branch and that is mutable (debatably a disadvantage as well, though in this case I'm not sure how it would harm older versions of the app)

Pretty sure these dependencies are evaluated statically at build time and baked into the app bundle.  It would only affect old versions of the app if re-build them. That said, this is very surprising to me. I do wonder whether it would be a best practice to make a new branch in this repo and explicitly update chalupa-mobile's package.json. Otherwise the changes to the app are not apparent from looking at the commit history of the mobile app.

> why not apply a fix in the main location so that it works as one would expect it to? Since we are passing en it's counter intuitive (IMO) that it would return results in any other language.

I don't disagree that this is counter-intuitive.  I think the reason why not is to keep our forked changes to a minimum. I already think we should be pulling in the newest version of this library (it has been updated to use hooks, among probably many other things).

>  Fixing it in the app means that we have to apply the fix in at least the following 2 methods
Couldn't we apply this logic in the `PlacesAutocomplete` component here https://github.com/convoyinc/chalupa-mobile/blob/master/src/search/components/PlacesAutocomplete.js#L125? If not, is there some other way we could consolidate this logic?

Aside, looks like the `details` are passed back to the mobile app in the callback. It seems to me that the core of this bug is that we're using `rowData.description` as the search input when we really want `details.formatted_address` -- since the latter will always be provided in the language specified (I guess?)

**Comment by NathanielWaggoner** [comment]
Hi Friends, just a couple comments here:

one of two things needs to happen here IMO.

1). Chalupa should be pointed at a specific hash.  We've been picking up any changes to ```v1.4.0-convoy-v2"``` since it was merged 4 months ago, without necesarily knowing it.

2). The policy on this repo should be "any new release change is a new branch". so this should be "v1.4.0-convoy-v3"

Eiher of these would force package updates in chalupa, which would stop us from having unpredictable build behavior against this dep.

Next question:

Can we just build our own component for this?  or bring it into chalupa directly?  The license is MIT, so i think we'r fine to just copy pasta it, it resolves this annoying dependency/fork thing.  I guess theoretically it makes it harder to take upstream changes, but per greg we're 50 commits behind anyway so why bother with the fork?

**Comment by NathanielWaggoner** [comment]
Also given this bug:

https://github.com/yarnpkg/yarn/issues/4734

I'm not sure if CI builds would actually pick up your change or not.

**Comment by chalenascholl** [comment]
> Pretty sure these dependencies are evaluated statically at build time and baked into the app bundle.
Ah yes, you're right.

> I think the reason why not is to keep our forked changes to a minimum.
A good argument :)

> Couldn't we apply this logic in the PlacesAutocomplete component [here](https://github.com/convoyinc/chalupa-mobile/blob/master/src/search/components/PlacesAutocomplete.js#L125)?
We could, which would functionally work but would still display the `description` string in the input because that is determined by `shortenedDescription`. I think it would make sense to have these behave the same way so I think we should apply the fix in both places

> It seems to me that the core of this bug is that we're using rowData.description as the search input when we really want details.formatted_address -- since the latter will always be provided in the language specified (I guess?)
Yes, but for thoroughness I think it makes sense to update `shortenedDescription` as well, which is `renderDescription` in this package and is not being passed `details` currently. It's an easy enough change, I just hadn't considered the other points you mentioned here when I decided to do it here. I'll close this out and switch it over to the mobile app

**Comment by chalenascholl** [comment]
@NathanielWaggoner 

> Either of these would force package updates in chalupa >

I can do one of them when I add my changes. Do you have a preference? A hash might be better since it would force anyone modifying it to update the hash even if they don't know the repo policy/best practice

> Can we just build our own component for this? or bring it into chalupa directly? The license is MIT, so i think we'r fine to just copy pasta it, it resolves this annoying dependency/fork thing. I guess theoretically it makes it harder to take upstream changes, but per greg we're 50 commits behind anyway so why bother with the fork? >

In an ideal word it would be better to build our own or bring it up to speed to take advantage of any improvements but I have a feeling this probably falls pretty low on the prioritization list unless we think either of these would speed up the performance of it?

**Pull request closed without merging**
